---
title: "Using the online server"
author: ""
date: ""
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

We will be using an online server to run the module exercises.
To get setup, we will provide you with username and password to access the server the first day of classes.

## Data sets

We have loaded data sets needed for the class exercises onto the server at `/data/SISG2023M15/data/`.

## Template R code

Template R code is available for some of the exercises to get your started; these are available in `/data/SISG2023M15/code/`.
We recommend you copy the files in this folder so you will be able to modify them when you try out the exercises.

## Using RStudio Server

We have started a RStudio server so you can start a Rstudio session from your web browser which will run on the online server.
To connect your browser to the online server:

Go to your web browser and enter `http://si2023-compute.biostat.washington.edu:8787/`.
You should be re-directed to the RStudio login page where you can enter your username/password.

Once logged in, the working directory will be your home directory.

**We strongly encourage you to use this** when doing the class exercises so it will be easier to run scripts from RStudio, load datasets as well as visualize plots. 

## Notes

Datasets and R template code are all available [in the Github repository](https://github.com/joellembatchou/SISG2023_Association_Mapping) 
(under the `data/` and `code/` subdirectories, respectively).
